payload:
  - DOMAIN-SUFFIX,steamcommunity.com
  - DOMAIN-SUFFIX,githubusercontent.com
  - DOMAIN-SUFFIX,pornhub.com
  - DOMAIN-SUFFIX,javdb.com
  - DOMAIN-SUFFIX,avbebe.com
  - DOMAIN-SUFFIX,missav.com
